# Generated by Django 2.1.5 on 2019-07-19 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def category_group(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    CategoryGroup = apps.get_model("main", "CategoryGroup")
    db_alias = schema_editor.connection.alias
    CategoryGroup.objects.using(db_alias).bulk_create([
        CategoryGroup(name="Special", group_type='Z'),
        CategoryGroup(name="Budget", group_type='A'),
        CategoryGroup(name="Credit", group_type='A'),
        CategoryGroup(name="Tracking", group_type='A'),
    ])

def account(apps, schema_editor):
    Account = apps.get_model("main", "Account")
    db_alias = schema_editor.connection.alias
    Account.objects.using(db_alias).bulk_create([
        Account(name="Manual adjustment", account_group=apps.get_model('main', 'CategoryGroup').objects.get(pk=1)),
    ])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('actual_balance', models.FloatField(blank=True, null=True)),
                ('account_type', models.CharField(blank=True, choices=[('Budget', (('BK', 'Bank'), ('CA', 'Cash'))), ('Credit', (('CC', 'Credit Card'), ('CL', 'Credit Line'))), ('Tracking', (('SA', 'Savings'), ('IN', 'Investments')))], max_length=2, null=True)),
                ('active', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('notes', models.CharField(max_length=140, null=True)),
                ('amount', models.FloatField()),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_entries', to='main.Account')),
                ('budget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Budget')),
            ],
            options={
                'verbose_name_plural': 'Budget Entries',
            },
        ),
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('group_type', models.CharField(blank=True, choices=[('I', 'Inflow'), ('O', 'Outflow'), ('A', 'Account'), ('Z', 'Other')], max_length=1, null=True)),
                ('ordering', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('cod', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='TransactionEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.IntegerField(null=True)),
                ('date', models.DateField()),
                ('entry_type', models.CharField(choices=[('T', 'Transaction'), ('S', 'Split'), ('C', 'Credit')], max_length=1)),
                ('description', models.CharField(blank=True, max_length=140, null=True)),
                ('amount', models.FloatField()),
                ('conciliated', models.BooleanField(default=True)),
                ('budget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Budget')),
                ('from_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_entries_from', to='main.Account')),
                ('to_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_entries_to', to='main.Account')),
            ],
            options={
                'verbose_name_plural': 'Transaction Entries',
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='account_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='main.CategoryGroup'),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='main.Currency'),
        ),
        migrations.RunPython(category_group),
        migrations.RunPython(account),
    ]
