# Generated by Django 2.1.5 on 2019-05-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionentry',
            name='transaction_id',
            field=models.IntegerField(null=True),
        ),
    ]
